/*
 * generated by Xtext
 */
package org.csu.idl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.csu.idl.xtext.ui.internal.IDLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IDLActivator.getInstance().getInjector(IDLActivator.ORG_CSU_IDL_XTEXT_IDL);
	}
	
}
