/*
 * generated by Xtext
 */
package org.csu.idl.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IDLRuntimeModule extends org.csu.idl.xtext.AbstractIDLRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
	  return IDLValueConverterService.class;
	}
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return IDLQualifiedNameProvider.class;
	}
}
