/*
 * generated by Xtext
 */
package org.csu.idl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IDLUiModule extends org.csu.idl.xtext.ui.AbstractIDLUiModule {
	public IDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
