/*
* generated by Xtext
*/
package org.csu.idl.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.csu.idl.xtext.services.IDLGrammarAccess;

public class IDLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IDLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.csu.idl.xtext.parser.antlr.internal.InternalIDLParser createParser(XtextTokenStream stream) {
		return new org.csu.idl.xtext.parser.antlr.internal.InternalIDLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "specification";
	}
	
	public IDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
