/*
* generated by Xtext
*/
package org.csu.idl.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class IDLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
