/*
* generated by Xtext
*/
package org.csu.idl.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IDLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.csu.idl.xtext.ui.internal.IDLActivator.getInstance().getInjector("org.csu.idl.xtext.IDL");
	}
	
}
