
/*
 * generated by Xtext
 */
 
package org.csu.idl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class IDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.csu.idl.xtext.ui.internal.IDLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.csu.idl.xtext.ui.internal.IDLActivator.getInstance().getInjector("org.csu.idl.xtext.IDL");
	}
	
}
