/*
* generated by Xtext
*/
package org.csu.idl.xtext.ui.contentassist;

import org.csu.idl.xtext.ui.contentassist.AbstractIDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IDLProposalProvider extends AbstractIDLProposalProvider {

}
